### ISSUE TITLE
empty email is not valid

### ISSUE THREAD

**Issue by ofirdagan** [wix/commons-validator-js#10]
`new EmailValidator().isValid('')` returns false.

IMO it should return true. Most of the times an empty email is ok. If it's a required field it should fail under another validation.

**Comment by dleshem** [comment]
This library deals with email address validation, not with form validation. The empty string is not a valid email address:
- It doesn't conform to [Addr-Spec in RFC5322](https://tools.ietf.org/html/rfc5322#section-3.4.1)
- It is not considered valid by the Java [Commons-Validator](http://commons.apache.org/proper/commons-validator/) that this library is a port of
- Gmail won't let you send to it.
