### ISSUE TITLE
Accepting wrong email domain id Ex.. "abcd@com"

### ISSUE THREAD

**Issue by yatinsmile** [wix/commons-validator-js#3]
Hello Team,

I have just implemented the commons-validator.js into angularJS validation by downloading it by bower.json.

I am using the "validator.isValid(modelValue)" function to validate email id, 

But I am surprise that it accepted the invalid email id "abcd@com" ): 
It is quite strange how to handle this scenario into validation..

Plz check & confirm is my findings are valid or invalid.

**Comment by wkillerud** [comment]
Actually that is a valid email format. The list of different formats for valid emails is long and strange, which makes email validation all the more difficult.

For a non-complete list of valid email formats take a look at Wikipedia: https://en.wikipedia.org/wiki/Email_address#Examples

The format "abcd@com" is number three from the bottom.

**Comment by dleshem** [comment]
This is indeed inconsistent with the Java [Apache Commons Validator](https://commons.apache.org/proper/commons-validator/), as

```
// In Java
ApacheEmailValidator.getInstance.isValid("abcd@com") // returns false
```

**Comment by dutzi** [comment]
+1!

**Comment by dleshem** [comment]
Fixed in https://github.com/wix/commons-validator-js/commit/febf94b8513a709edb3e8e0aa08d834034c1d855

Consistent with Apache Commons Validator, this implementation of EmailValidator's constructor now accepts an allowTld argument (default: false).
