### ISSUE TITLE
Uncaught Error: Cannot find module "babel-runtime/helpers/classCallCheck"

### ISSUE THREAD

**Issue by nathancharles** [wix/commons-validator-js#4]
It seems babel is adding it's runtime helpers as external dependencies in the output code.
https://babeljs.io/docs/plugins/transform-runtime/#helper-aliasing

This is causing commons-validator-js to fail when being imported as these dependencies cannot be found in the consuming application

**Comment by dleshem** [comment]
Fixed in https://github.com/wix/commons-validator-js/commit/f1c0bbc5005efd50e31126b17eebe22c2d64267e
