### ISSUE TITLE
Punycode dependency isn't transpiled

### ISSUE THREAD

**Issue by nathancharles** [wix/commons-validator-js#7]
When using commons-validator-js in the browser, it is pulling in punycode which isn't transpiled, causing errors in browsers without robust es6 support.

From the punycode.js release notes:
"This release drops support for old environments. Punycode.js v2.0.0 targets Node.js v6+ and nothing else. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see v1.4.1."

**Comment by dleshem** [comment]
Good catch, thanks!
