### ISSUE TITLE
Doesn't work with yarn

### ISSUE THREAD

**Issue by 3LOK** [wix/commons-validator-js#9]
Trying to install this package on yarn by:

```
yarn add commons-validator-js
```

results in:
```
error Couldn't find package "bower-auto-release" on the "npm" registry.
```

This is probably due to the optionalDependencies currently not supported by yarn. As I'm not sure what are yarn's plans on optionalDependencies, and since I really love yarn, but also need to use commons-validator-js in my project, it will be nice if you could find a solution for this.

Thanks.

**Comment by dleshem** [comment]
Fixed in https://github.com/wix/commons-validator-js/commit/911b6fe0eb27c220fd66c5897b5a14d12258634b
